### ISSUE TITLE
DRY Principle

### ISSUE THREAD

**Issue by DmytrPr** [Melnikiva/renju#2]
Avoid repeated code. The while loop in the getGameResults can be extracted into a separate helper function to avoid repetitions.

https://github.com/Melnikiva/renju/blob/59b221daf5f1ea8b919674681aa5e38c5f9de08b/renju.js#L66-L78

**Comment by Melnikiva** [comment]
It is hard to maintain DRY principle in this case, because we are using functions instead of classes, so we don't have permanent storage for all necessary values such as n, x, y, player and board array, so we would pass these values as function parameters, and it is not pretty as you can imagine. Yes, we definitely can implement this approach, but IMO this is useless in this exact case.
It is better to build this application using class, but it requires rebuilding all structure.

**Comment by Melnikiva** [comment]
In the end, we completely removed the second while loop, as we don't actually need it.
